### ISSUE TITLE
Search page UI

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#1]
Trzeba zrobić widok dla strony wyszukiwania. Proponowałbym takie rozwiązanie:
* bezpośrednio w search-page.component.html wkładamy input do wprowadzenia tesktu (póki co umówmy się, że będzie to tylko nazwa rekordu, może uda się potem zrobić to wyszukiwanie pełnotekstowe to będzie tam szedł wtedy cały tekst). Niech to będzie w tagu <form>, do tego przycisk submit. Submit będzie wywoływał serwis wysyłający zapytanie wyszukiwania. Po otrzymaniu odpowiedzi, będzie wyświetlana albo informacja o niepowodzeniu albo lista znalezionych rekordów.
* Póki co, można zahardkodować listę rekordów jakąś w komponencie i po prostu po kliknięciu submit, żeby wyświetlał się widok z tą listą. Jak to będzie banglało to dodamy serwis. Równolegle trzeba ten serwis napisać i napisać też coś co będzie nam parsowało odpowiedź na jakiś model (Issue 2).
* Lista mini-snippetów rekordów jako oddzielny komponent, mini snippet również, wyświetlanie całego snippeta kolejny, i snippety załączników kolejny. Tak będzie przejrzyście i nie będzimy mieli jednego trzykilometrowego htmla. Proponuję, żeby to działało tak: klikasz na details któregoś mini-snippeta na liście i to generuje event podając w treści rekord, jakiemu odpowiada, search-page-component nasłuchuje sobie na ten event i jak go otrzyma, to ustawia otrzymany rekord komponentowi wyświetlania snippeta dużego. Przyciski details przy załącznikach powinny tylko rozwijać i zwijać szczegóły i tyle, to już bez jakiegoś dodatkowego komponentu.
* Do dużego snippeta rekordu dodać przycisk "download", który będzie łączył się z odpowiednim serwisem (Issue 9)

Jak będą jakieś pytania to piszczcie komentarze tutaj pod issue a nie na slacku, bo tam zginie!

Zrobiłem dwa super mockupy do pomocy. Powodzenia.

![search_found](https://cloud.githubusercontent.com/assets/18700263/26722514/959dfa52-4790-11e7-92f9-ce917dedb704.png)
![search_notfound](https://cloud.githubusercontent.com/assets/18700263/26722515/98fe2bc2-4790-11e7-9552-a8368cdf975b.png)

**Comment by kamil-gawlik** [comment]
done
