### ISSUE TITLE
Wyszukiwanie pełnotekstowe - jak to u nas zaimplementować i czy warto?

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#10]

**Comment by kamil-gawlik** [comment]
gdzie dokładnie jest w tym momencie realizowane wyszukliwanie?

**Comment by majcherpiotrek** [comment]
"Wyszukiwanie" jest realizowane w którymś kontrolerze teraz z użyciem Mongolia repository albo grid fs

**Comment by kamil-gawlik** [comment]
zrobiłem pełnotekstowe, musi być pełne słowo z property oznaczonego jako @TextIndexed  a klasa musi byc oznaczona @Document
