### ISSUE TITLE
Animacja pokazująca, że czkeamy na odpowiedź serwera przy wyszukiwaniu

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#17]
W search page'u jest tak, że request wysyłany jest na każde klinknięcie klawisza. Niestety dopóki nie dostaniemy response'a żadnego, wygląda to tak od strony użytkownika, jakby program się zawiesił, albo nic nie robił. Myślę, że to fajny feature, żeby dynamicznie odpytywało, a nie tylko po naciśnięciu search. ALE:
* przydałaby się jakaś animacja, taki kręciołek czy coś, na środku ekranu, tam gdzie potem ma się pojawić snippet, która pokazałaby że coś się zadziało po wpisaniu
* dodałbym search button tak czy siak, któy też by wysyłał request - popatrzcie jak jest w googlu, w trakcie pisania już ci wyszukuje, ale przycisk wyszukania też jest i na enter też wysyła request

**Comment by kamil-gawlik** [comment]
Moge zrobić potrzebny mi jednak pull request widoku wyszukiwania

**Comment by majcherpiotrek** [comment]
niestety nie ma już czasu na takie bajery
