### ISSUE TITLE
Odbieranie DTO od backendu 

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#2]
Trzeba znaleźć sposób na przetworzenie odebranego JSON'a na model w naszym kliencie. Najfajniej by było, jakby to się robiło jakoś z automatu, bez pisania jakiś parserów. Ale jeśli nie znajdziemy takiego rozwiązania, to trzeba będzie napisać parser, który będzie iterował po wszyskich kluczach jsona i wpisywał je w pola modelu. Nie ważne czy będzie parser, czy jakaś zgrabniejsza metoda już gotowa, dodać tę funkcjonalność jako serwis i dodać w app.module jako provider.

**Comment by kamil-gawlik** [comment]
Biorę.
To nie będize po prostu serwis dziłający po http na zasadzie http.get(url)=> return <jakiś obiekt w postaci klasy>?

**Comment by majcherpiotrek** [comment]
Tak właśnie by spoko było, tylko właśnie nie wiem jak ten obiekt stworzyć z automatu.  Tzn. jak to zrobić, żeby on od razu zmapował się na jakiś RecordModel czy coś.

**Comment by kamil-gawlik** [comment]
mam na myśli coś takiego: https://stackoverflow.com/questions/34516332/angular2-cast-a-json-result-to-an-interface

gorszą opcją ale możliwą jest: https://stackoverflow.com/questions/22885995/how-do-i-initialize-a-typescript-object-with-a-json-object/22886730#22886730
