### ISSUE TITLE
Wysyłanie DTO do backendu

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#4]
Teraz backend odbiera stringo-jsony i parsuje je na nasze metadane. Może jest jakiś zgrabny sposób na wysyłanie tego jako jakiś data transfer object (DTO), co ułatwiłoby obsługę wszystkiego na backendzie i zabezpieczyło apkę przed wysypywaniem takim jak np. w issue 3. Nie robiłem wcześniej nigdy tego, więc na pewno da się to zrobić lepiej, jak ktoś wie jak to dawać.

**Comment by kamil-gawlik** [comment]
Moim zdaniem złe podejście, nie dasz rady wysłać obiektu, no chyba że bawilibyśmy się w serializacje. Możemy tylko sprawić, by zamiast konstruować ręcznie jsona był wysyłany obiekt reprezentujący go w aplikacji (np RecordModel)

**Comment by majcherpiotrek** [comment]
Wysyłanie RecordDetailsModel poprzez stringa i parsowanie z powrotem na backendzie działa bez zarzutu. Nie ma czasu na polepszanie tego rozwiązania - trzeba by zmieniać w wielu miejscach.
