### ISSUE TITLE
Refactor upload page

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#6]
Piszący się na bieżąco snippet rekordu nie wygląda dobrze, należałoby zrobić tak:
* Na początku mamy tylko główny formularz, wpisujemy metadane całego rekordu, dodajemy pliki. 
* Po kliknięciu "add record" znika formularz i pojawia się snippet rekordu. Nad listą plików powinien być jakiś jednoznaczny prompt zachęcający do dodania metadanych do plików. Poniżej wielki, czerwony button "upload record", po wciśnięciu którego pójdzie dopiero request.
* Po wysłaniu requestu powinien pojawić się informacja o sukcesie + snippet wstawionego właśnie rekordu, lub informacja o błędzie i przycisk umożliwiający ponowną próbę wysłania rekordu. 
* Niezelażnie czy request zakończył się sukcesem, czy nie, pod spodem powinien pojawić się przycisk "add another rekord", tak jak jest już teraz w sumie.

Dodam jak będę miał chwilę jakieś profesjonalne mockupy z painta.

**Comment by olo95** [comment]
Nie mogę się przypisać do tego issue nie wiem dlaczego.
@piotrmajcher94
