### ISSUE TITLE
Endpoint do pobierania całego rekordu w formacie zip

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/dg-repo#8]
Trzeba wystawić endpointa, który umożliwiałby ściąganie całego rekordu w formacie zip. Powinien przyjmować id rekordu jako parametr.

**Comment by adam-wudzinski** [comment]
Endpoint: /api/records/zip?record-id=
Pobiera zipa ze wszystkimi zalącznikami danego rekordu
